linters:
  enable-all: true
  disable:
  - containedctx
  - exhaustruct
  - exhaustivestruct
  - tagliatelle

linters-settings:
  varnamelen:
    ignore-decls:
    - w http.ResponseWriter
    - r *http.Request
